# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def all_pods
  pod 'SnapKit'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
end

target 'HansungRentSystem_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HansungRentSystem_iOS
  pod "ViewAnimator"
  pod 'SnapKit'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

end
