# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HansungRentSystem_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HansungRentSystem_iOS
  pod 'SnapKit'


end
